### ISSUE TITLE
Not all task is completed

### ISSUE THREAD

**Issue by riffalutama** [Widiskel/initia-daily-bot#11]
![image](https://github.com/Widiskel/initia-daily-bot/assets/35131092/e791a7ce-3d57-493f-a428-b7bb3c29d85e)

these tasks isn't completed, isn't that there is a feature to do it?

**Comment by Widiskel** [comment]
the bot now focused on earning daily exp from secret task, you can complete weekly task manually if it not completed by bot.

as you can see weekly task give you 600exp weekly if all completed
but , except from weekly task there a secret task for earning exp. that the way you earn exp daily.

because no benefit if bot keep spamming tx on weekly task if it completed already, no reward will be granted.

remember to keep initia-daily-bot up do date.
